version: '3.8'

services:
  voice-assistant-api:
    build: .
    container_name: voice-assistant-chatbot
    ports:
      - "8089:8089"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    volumes:
      # Mount audio directories to persist generated files
      - ./audio_response_path:/app/audio_response_path
      - ./temp:/app/temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8089/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - voice-assistant-network

networks:
  voice-assistant-network:
    driver: bridge

volumes:
  audio_data:
    driver: local
