networks:
  app-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Willmo
    expose:
      - '8000'
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - ./audio:/app/audio  # Mount audio folder in app container

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy_willmo
    ports:
      - '0.0.0.0:8089:80'
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./audio:/app/audio
    depends_on:
      - app